name: Test and Build CI
on: [push, pull_request]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install ğŸ”¨
        run: |
          npm install

      - name: Format and Lint ğŸ”§
        run: |
          npm run format
          npm run lint
          npm run test

      - name: Build âš™ï¸
        run: |
          npm run build